sudo: required
services:
  - docker

matrix:
    allow_failures:

cache: bundler

install:
    - docker build -t rock/orocos-rb .
    - docker run -d rock/orocos-rb tail -f /dev/null
    - docker ps -a

# overwrite the default build command
script:
    - docker run rock/orocos-rb /bin/bash -c "source /home/docker/rock_test/env.sh; cd tools/orocos.rb; rake test"
